# Generated by Django 5.1.3 on 2024-11-20 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
        ('puesto', '0002_alter_puesto_sueldo_quincenal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='puesto.puesto'),
        ),
    ]
