# Generated by Django 5.1.3 on 2024-11-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PERCEPCION', 'percepcion'), ('DEDUCCION', 'deduccion')], max_length=20)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
