# Generated by Django 5.1.3 on 2024-11-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puesto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='sueldo_quincenal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
