# Generated by Django 5.1.3 on 2024-11-20 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_percepciones', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_deducciones', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_neto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empleado.empleado')),
            ],
        ),
    ]
