# Generated by Django 5.1.3 on 2024-11-20 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_empleado_puesto'),
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='empleado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='empleado.empleado'),
        ),
    ]
