# Generated by Django 5.1.3 on 2024-11-20 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_initial'),
        ('empleado', '0002_alter_empleado_puesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='empleado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='empleado.empleado'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
