# Generated by Django 5.1.3 on 2024-11-20 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concepto_nomina', '0001_initial'),
        ('puesto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuestoConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='concepto_nomina.conceptonomina')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='puesto.puesto')),
            ],
        ),
    ]
